backend:
  name: git-gateway
  branch: main

media_folder: static/img
public_folder: /img

collections:
  - name: menu
    label: Speisekarte
    files:
      - file: src/content/pages/menu.md
        label: Speisekarte
        name: menu
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - {
              label: "Beschreibung",
              name: "description",
              widget: "text",
              required: false,
            }
          - {
              label: "Bild",
              name: "thumbnail",
              widget: "image",
              required: false,
            }
          - { label: "Inhalt", name: "body", widget: "markdown" }

  - name: opening-hours
    label: Öffnungszeiten
    files:
    - file: src/content/settings/opening-hours.md
      label: Öffnungszeiten
      name: opening-hours
      fields:
        - { label: "Title", name: "title", widget: "string" }
        - label: "Öffnungszeiten"
          name: "opening_hours"
          widget: list
          fields:
            - { label: "Tage", name: "days", widget: "string" }
            - { label: "Uhrzeit", name: "hours", widget: "string" }

  - name: pages
    label: Seiten
    files:
      - file: "src/content/pages/impressum/index.md"
        label: Impressum
        name: impressum
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - {
              label: "Beschreibung",
              name: "description",
              widget: "string",
              required: false,
            }
          - { label: "Inhalt", name: "body", widget: "markdown" }

      - file: "src/content/pages/datenschutz/index.md"
        label: Datenschutz
        name: datenschutz
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - {
              label: "Beschreibung",
              name: "description",
              widget: "string",
              required: false,
            }
          - { label: "Inhalt", name: "body", widget: "markdown" }
